apiVersion: v1
kind: Pod
metadata:
  name: matheustreviz-nodejs
  labels:
    app: matheustreviz-nodejs
spec:
  containers:
    - name: container-pod-nodejs
      image: matheustreviz/validador-cpf-java-turma-devops
      ports:
        - containerPort: 3000

# kubectl apply -f pod-nginx.yml
# kubectl describe -f pod-nginx.yml
# kubectl delete -f pod-nginx.yml
